websocket basics implemented
ONTechNITS/RapidHTML pull request #15
Opened 2024-08-05 18:01 UTC by moseye

roast me

closes #5

2024-08-05 22:21 UTC, ThomasJRyan submitted a review, later dismissed

2024-08-06 04:28 UTC, ThomasJRyan requested changes
Am I crazy or did the unit tests disappear?

2024-08-06 04:32 UTC, ThomasJRyan approved these changes

2024-08-06 04:33 UTC, moseye commented
> Am I crazy or did the unit tests disappear?

must've been the wind

2024-08-06 14:50 UTC, rashidnhm approved these changes
Looks good! Haven't worked with WS in a while so a little rusty on that.

Would it be helpful to have docs to show how this hotreload works? Doesn't have to be part of this PR

2024-08-06 14:50 UTC, rashidnhm commented on tests/test_ws.py
> +    test_app = QuickHTML()
Not needed within this PR, but we probably want this to become a fixture in the near future to make things easier

2024-08-06 15:16 UTC, moseye commented on src/quickhtml/routing.py
> +            None: This method does not return anything.
Nah not needed - I can remove it. Was left over from the generated docs

2024-08-08 02:40 UTC, ThomasJRyan approved these changes

2024-08-09 02:43 UTC, merged