Moses/4 live reload
ONTechNITS/RapidHTML pull request #22
Opened 2024-08-06 16:25 UTC by moseye

2024-08-09 03:52 UTC, ThomasJRyan requested changes
Is there any way for us to unittest this...

2024-08-09 03:52 UTC, ThomasJRyan commented on src/rapidhtml/app.py
> +        setTimeout(function () {
Is `setTimeout` necessary? I can remove it with seemingly no ill effects. If it is necessary, we need to reduce the timeout to something much smaller (I was able to set it to 0 with no issues). Having to wait five seconds for the page to reload isn't ideal

2024-08-09 03:52 UTC, ThomasJRyan commented on src/rapidhtml/app.py
> +    console.log(`connected`);
Might as well be cute about it
```suggestion
    console.log(`Connected to the RapidHTML development server!`);
```

2024-08-09 03:52 UTC, ThomasJRyan commented on src/rapidhtml/app.py
> +    if (active) {
Might not need `active` either actually? Same thing, no issues for me locally

2024-08-09 03:52 UTC, ThomasJRyan commented on src/rapidhtml/app.py
> +    ) -> None:
Probably time for a docstring
```suggestion
    ) -> None:
    """Initializes the RapidHTML application.

        Args:
            html_head (typing.Iterable, optional): Tags to inject into each 
                page's <head>. Defaults to None.
            reload (bool, optional): Enables live-reloading. Defaults to False.
    """
```

2024-08-09 03:53 UTC, rashidnhm commented on src/rapidhtml/app.py
> +        appname = Path(inspect.currentframe().f_back.f_globals.get("__file__", "")).stem
Would:
`Path(__file__).stem` work? Or do you HAVE TO go one frame up?

2024-08-09 04:20 UTC, rashidnhm commented on src/rapidhtml/app.py
> +        appname = Path(inspect.currentframe().f_back.f_globals.get("__file__", "")).stem
Tried it, won't work

2024-08-09 04:24 UTC, ThomasJRyan submitted a review, later dismissed
Would also be nice if something was written about this in the docs

2024-08-09 04:26 UTC, ThomasJRyan commented
This requires `app.serve()` to be inside of `if __name__ == "__main__"`. Would be nice if that could be worked around somehow

2024-08-09 04:27 UTC, rashidnhm commented on src/rapidhtml/app.py
>      def serve(self, *args, **kwargs):
It's possible for the user to pass `reload=` here as well. We should pop it out and raise a Warning.

2024-08-10 23:29 UTC, moseye commented
> This requires `app.serve()` to be inside of `if __name__ == "__main__"`. Would be nice if that could be worked around somehow

Unfortunately not possible due to how uvicorn is handling reloading the app. From my understanding the current flow is as such
1. We start main.py, which calls app.serve()
2. Uvicorn runs, and sees live-reloading is selected, configures sockets, and then goes to reload and attempt to load main.py again.
3. If main.py has an app.serve, it starts this process all over again, and since the configured IP address and socket are already used, it errors out.

I tried to fix this but it was becoming very hacky and jank. If either of you @rashidnhm @ThomasJRyan have any ideas im open, but I think enforcing an if main block is not a big deal.

2024-08-11 21:04 UTC, ThomasJRyan submitted a review, later dismissed

2024-08-11 21:04 UTC, ThomasJRyan commented on src/rapidhtml/app.py
> +    def serve(self, appname=None, host="127.0.0.1", port=8001, *args, **kwargs):
I think it should be 8000. It's the default for uvicorn and I initially used 8001 due to the port being taken and messed up by pushing the wrong example code
```suggestion
    def serve(self, appname=None, host="127.0.0.1", port=8000, *args, **kwargs):
```

2024-08-11 21:04 UTC, ThomasJRyan commented on tests/test_live_reload.py
Would the TestClient be applicable here?
https://www.starlette.io/testclient/

If not it's fine. So long as the tests cover what they're supposed to all's good

2024-08-11 21:08 UTC, moseye commented on tests/test_live_reload.py
Tried originally, seems unable to use live-reloading unfortunately.

2024-08-11 23:35 UTC, ThomasJRyan approved these changes

2024-08-12 01:09 UTC, merged